name = "webpage-score-renderer"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[env.production]
# Browser Rendering binding
[[env.production.browser]]
binding = "BROWSER"

# Environment variables
[vars]
RENDER_TOKEN = "your-secure-token-here"
